Create dude.js
arya-s/nocchi pull request #61
Opened 2017-05-08 07:27 UTC by dude22072

New command: dude

2017-05-13 16:26 UTC, arya-s commented
what's the usecase for this?

2017-05-13 19:18 UTC, dude22072 commented
It's been a long-running meme that several members of saw's server will say my name as dude{random numbers}, so I've made it easier on them.

2017-05-14 05:04 UTC, arya-s requested changes

2017-05-14 05:04 UTC, arya-s commented on src/commands/dude.js
> +  }
We are not running out of new lines :)

2017-05-14 05:04 UTC, arya-s commented on src/commands/dude.js
> +    var response="dude";
Strings should use single quotes.
Please add whitespace between `=`.

2017-05-14 05:04 UTC, arya-s commented on src/commands/dude.js
> +    var length=getRandom(5, 100);
Please add whitespace between `=`.

2017-05-14 05:04 UTC, arya-s commented on src/commands/dude.js
> +    for(var i=0;i<length;i++) {
Please add whitespace.

2017-05-14 05:04 UTC, arya-s commented on src/commands/dude.js
> +        response+=getRandom(0,9);
Please add whitespace.

2017-05-14 05:04 UTC, arya-s commented on src/commands/dude.js
> +    response += "?";
Strings should use singlequotes.

2017-05-14 05:23 UTC, merged